# Generated by Django 5.1.4 on 2024-12-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='WordPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(blank=True, null=True)),
                ('word', models.CharField(max_length=100)),
                ('number_errors', models.IntegerField(default=0)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpairs', to='api.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=100)),
                ('transcription', models.CharField(blank=True, max_length=100, null=True)),
                ('word_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.wordpair')),
            ],
        ),
    ]
